export interface TutorialStep {
  id: string;
  title: string;
  description: string;
  target: string;
  position: 'top' | 'bottom' | 'left' | 'right' | 'center';
  action?: 'click' | 'input' | 'navigate';
  view?: 'dashboard' | 'tournaments' | 'players' | 'teams' | 'export' | 'calendar';
  highlightMultiple?: boolean;
}

export const tutorialSteps: TutorialStep[] = [
  {
    id: 'welcome',
    title: 'Ласкаво просимо до ArbiChief!',
    description: 'Цей туторіал допоможе вам ознайомитися з усіма функціями додатку для організації шахових та шашкових турнірів.',
    target: '',
    position: 'center',
  },
  {
    id: 'header',
    title: 'Заголовок додатку',
    description: 'Тут відображається назва додатку та кнопка перемикання теми (світла/темна). Спробуйте натиснути на іконку місяця або сонця.',
    target: '[data-tutorial="header"]',
    position: 'bottom',
  },
  {
    id: 'theme-toggle',
    title: 'Перемикання теми',
    description: 'Натисніть цю кнопку, щоб перемкнути між світлою та темною темою. Ваш вибір збережеться для наступних сеансів.',
    target: '[data-tutorial="theme-toggle"]',
    position: 'bottom',
    action: 'click',
  },
  {
    id: 'navigation',
    title: 'Навігаційне меню',
    description: 'Використовуйте це меню для переходу між різними розділами додатку. На мобільних пристроях воно відображається знизу.',
    target: '[data-tutorial="navigation"]',
    position: 'right',
  },
  {
    id: 'dashboard',
    title: 'Панель керування',
    description: 'Тут ви бачите загальну статистику: кількість активних турнірів, гравців, команд та найближчі нагадування.',
    target: '[data-tutorial="dashboard-stats"]',
    position: 'bottom',
    view: 'dashboard',
  },
  {
    id: 'upcoming-reminders',
    title: 'Найближчі нагадування',
    description: 'Ця секція показує ваші найближчі нагадування про турніри. Ви можете додати нагадування при створенні або редагуванні турніру.',
    target: '[data-tutorial="upcoming-reminders"]',
    position: 'top',
    view: 'dashboard',
  },
  {
    id: 'nav-tournaments',
    title: 'Розділ турнірів',
    description: 'Перейдемо до розділу турнірів, де ви можете створювати та керувати турнірами.',
    target: '[data-tutorial="nav-tournaments"]',
    position: 'right',
    action: 'navigate',
    view: 'tournaments',
  },
  {
    id: 'create-tournament',
    title: 'Створення турніру',
    description: 'Натисніть цю кнопку, щоб створити новий турнір. Ви зможете налаштувати формат, систему жеребкування, правила підрахунку очок та тай-брейки.',
    target: '[data-tutorial="create-tournament"]',
    position: 'left',
    view: 'tournaments',
  },
  {
    id: 'tournament-filters',
    title: 'Фільтри турнірів',
    description: 'Використовуйте ці фільтри для швидкого пошуку турнірів за статусом: всі, активні, завершені або архівовані.',
    target: '[data-tutorial="tournament-filters"]',
    position: 'bottom',
    view: 'tournaments',
  },
  {
    id: 'tournament-card',
    title: 'Картка турніру',
    description: 'Кожна картка показує основну інформацію про турнір: назву, формат, статус, кількість учасників та дати. Натисніть на картку для детального перегляду.',
    target: '[data-tutorial="tournament-card"]',
    position: 'top',
    view: 'tournaments',
  },
  {
    id: 'nav-players',
    title: 'Розділ гравців',
    description: 'Тепер перейдемо до розділу гравців, де ви можете керувати базою даних учасників.',
    target: '[data-tutorial="nav-players"]',
    position: 'right',
    action: 'navigate',
    view: 'players',
  },
  {
    id: 'add-player',
    title: 'Додавання гравця',
    description: 'Натисніть тут, щоб додати нового гравця. Ви можете ввести ім\'я, прізвище, по батькові, унікальний код, рейтинг та стать.',
    target: '[data-tutorial="add-player"]',
    position: 'left',
    view: 'players',
  },
  {
    id: 'player-search',
    title: 'Пошук гравців',
    description: 'Використовуйте цей рядок пошуку для швидкого знаходження гравців за ім\'ям, прізвищем або унікальним кодом.',
    target: '[data-tutorial="player-search"]',
    position: 'bottom',
    view: 'players',
  },
  {
    id: 'player-table',
    title: 'Таблиця гравців',
    description: 'Тут відображаються всі гравці з їхніми даними. Ви можете сортувати за будь-яким стовпцем, редагувати або видаляти гравців.',
    target: '[data-tutorial="player-table"]',
    position: 'top',
    view: 'players',
  },
  {
    id: 'nav-teams',
    title: 'Розділ команд',
    description: 'Перейдемо до розділу команд для командних турнірів.',
    target: '[data-tutorial="nav-teams"]',
    position: 'right',
    action: 'navigate',
    view: 'teams',
  },
  {
    id: 'create-team',
    title: 'Створення команди',
    description: 'Тут ви можете створити команду, призначити гравців на дошки та встановити резервних гравців для командних турнірів.',
    target: '[data-tutorial="create-team"]',
    position: 'left',
    view: 'teams',
  },
  {
    id: 'team-composition',
    title: 'Склад команди',
    description: 'Кожна картка команди показує гравців на різних дошках та резервний склад. Це важливо для правильного підрахунку командних очок.',
    target: '[data-tutorial="team-card"]',
    position: 'top',
    view: 'teams',
  },
  {
    id: 'nav-calendar',
    title: 'Календар нагадувань',
    description: 'Перейдемо до календаря, де ви можете бачити всі нагадування з усіх турнірів в одному місці.',
    target: '[data-tutorial="nav-calendar"]',
    position: 'right',
    action: 'navigate',
    view: 'calendar',
  },
  {
    id: 'calendar-view',
    title: 'Перегляд календаря',
    description: 'Календар показує всі ваші нагадування про турніри. Дні з нагадуваннями позначені точками. Натисніть на день, щоб побачити деталі.',
    target: '[data-tutorial="calendar-grid"]',
    position: 'bottom',
    view: 'calendar',
  },
  {
    id: 'calendar-navigation',
    title: 'Навігація по місяцях',
    description: 'Використовуйте ці кнопки для перегляду попередніх або наступних місяців, або швидкого повернення до поточного дня.',
    target: '[data-tutorial="calendar-nav"]',
    position: 'bottom',
    view: 'calendar',
  },
  {
    id: 'upcoming-list',
    title: 'Список найближчих подій',
    description: 'Тут відображаються найближчі 5 нагадувань, відсортовані за датою та часом. Це допомагає швидко побачити, що буде далі.',
    target: '[data-tutorial="upcoming-list"]',
    position: 'top',
    view: 'calendar',
  },
  {
    id: 'nav-export',
    title: 'Розділ експорту',
    description: 'Перейдемо до розділу експорту, де ви можете зберігати та завантажувати дані турнірів.',
    target: '[data-tutorial="nav-export"]',
    position: 'right',
    action: 'navigate',
    view: 'export',
  },
  {
    id: 'export-formats',
    title: 'Формати експорту',
    description: 'Ви можете експортувати турніри у форматі JSON (для резервного копіювання) або CSV (для таблиць Excel).',
    target: '[data-tutorial="export-section"]',
    position: 'bottom',
    view: 'export',
  },
  {
    id: 'import-tournament',
    title: 'Імпорт турніру',
    description: 'Натисніть тут, щоб імпортувати раніше збережений турнір з JSON файлу. Це корисно для відновлення даних або використання шаблонів.',
    target: '[data-tutorial="import-button"]',
    position: 'left',
    view: 'export',
  },
  {
    id: 'tournament-details',
    title: 'Деталі турніру',
    description: 'Коли ви відкриваєте турнір, ви бачите вкладки: Учасники (додавання гравців), Жеребкування (генерація пар), Турнірна таблиця (результати), та Нагадування.',
    target: '',
    position: 'center',
  },
  {
    id: 'pairing-generation',
    title: 'Генерація жеребкування',
    description: 'Після реєстрації учасників натисніть "Генерувати тури" для автоматичного створення пар згідно з обраною системою (швейцарська або кругова).',
    target: '',
    position: 'center',
  },
  {
    id: 'results-entry',
    title: 'Введення результатів',
    description: 'Натискайте на матчі для введення результатів (1-0, 0-1, 0.5-0.5). Турнірна таблиця оновлюється автоматично з тай-брейками.',
    target: '',
    position: 'center',
  },
  {
    id: 'reminders-tab',
    title: 'Вкладка нагадувань',
    description: 'У вкладці нагадувань ви можете створювати одноразові або повторювані нагадування (щоденні, щотижневі, щомісячні) для кожного турніру.',
    target: '',
    position: 'center',
  },
  {
    id: 'complete',
    title: 'Вітаємо!',
    description: 'Ви завершили туторіал! Тепер ви знаєте всі основні функції ArbiChief. Ви можете переглянути туторіал знову в будь-який час з панелі керування.',
    target: '',
    position: 'center',
  },
];
